networks:
  dev:
version: '3.8'
services:
  redis:
    image: redis:alpine
    env_file:
      - ./.env
    restart: on-failure
    ports:
      - "6379:6379"
    networks:
      - dev
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    restart: always
    depends_on:
      - redis
    ports:
      - "8071:8080"
    networks:
      - dev
    volumes:
      - telegram_bot_AI_data:/var/www/telegram_bot_AI_data



volumes:
  telegram_bot_AI_data: