networks:
  dev:
version: '3.9'
services:
  redis:
    image: redis:alpine
    env_file:
      - ./.env
    restart: on-failure
    ports:
      - "6374:6379"
    networks:
      - dev
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    restart: always
    depends_on:
      - redis
    ports:
      - "8071:8080"
    networks:
      - dev
    volumes:
      - ./database.db:/var/www/AI_Telegram_bot/database.db


volumes:
  telegram_bot_AI_data: